services:
  web:
    image: project1
    container_name: project1-container
    environment: 
      - MY_PORT=7000
      - DB_URL=jdbc:mysql://34.130.82.82:3306/Docker
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - 7000:7000
  emailapp:
    image: emailapp
    container_name: emailapp-container
    ports:
      - 8000:8000
    environment: 
      - MY_PORT=7000
      - DB_URL=jdbc:mysql://34.130.82.82:3306/Docker
      - DB_USERNAME=root
      - DB_PASSWORD=password
  dbmysql:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Docker