services:
  web:
    image: project1
    container_name: project1-container
    restart: always
    environment:
      - MY_PORT=7000
      - DB_URL=jdbc:mysql://34.130.82.82:3306/Docker
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - 7000:7000
    depends_on:
      - dbmysql
  dbmysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Docker